from pathlib import Path
p=Path('src/pages/AuthContainer.tsx'); s=p.read_text()
def r(a,b,n=1):
 global s
 if s.count(a)!=n: raise SystemExit(f'mismatch: {a[:100]!r}')
 s=s.replace(a,b,n)
r("import React, { useEffect, useState } from 'react';","import React, { useEffect, useState } from 'react';\nimport { supabase } from '../supabase/supabaseClient';")
r("  const [isBootstrapping, setIsBootstrapping] = useState(true);","  const [isBootstrapping, setIsBootstrapping] = useState(true);\n  const [authSession, setAuthSession] = useState<any>(null);")
r("        const backendReachable = await probeBackendReachable();\n        setOfflineMode(!backendReachable);\n\n        if (!backendReachable) {\n          setScreen('login');\n          setAuthError('Offline Mode');\n        }\n\n        if (!storedToken) {\n          clearCorruptLocalState();\n          setScreen('login');\n        }\n\n        if (backendReachable && storedToken) {","        const { data: sessionData, error: sessionError } = await supabase.auth.getSession();\n        if (sessionError) throw sessionError;\n        const session = sessionData.session;\n        setAuthSession(session);\n        const backendReachable = await probeBackendReachable();\n        setOfflineMode(!backendReachable);\n        if (session && storedToken) {")
r("        if (backendReachable && launchPayload?.targetScreen === 'chat') {","        if (session && launchPayload?.targetScreen === 'chat') {")
r("        } else if (backendReachable && launchPayload?.targetScreen === 'profile') {","        } else if (session && launchPayload?.targetScreen === 'profile') {")
r("        } else if (backendReachable && launchPayload?.targetScreen === 'settings') {","        } else if (session && launchPayload?.targetScreen === 'settings') {")
r("        if (backendReachable && pendingPushToken) {","        if (session && backendReachable && pendingPushToken) {")
r("        setScreen('login');\n        setOfflineMode(true);\n        setAuthError('Offline Mode');","        setScreen('login');\n        setAuthSession(null);\n        setAuthError(error instanceof Error ? error.message : 'Authentication could not be restored. Please log in again.');")
r("    void bootstrap();\n    const unsubscribe = subscribeToOpenScreen((payload) => {\n      setScreen('dashboard');","    void bootstrap();\n    const { data: authSubscription } = supabase.auth.onAuthStateChange((_event, session) => {\n      setAuthSession(session);\n      if (!session) {\n        setScreen('login');\n        setActiveTab('home');\n      }\n    });\n    const unsubscribe = subscribeToOpenScreen((payload) => {\n      if (!authSession) { setScreen('login'); return; }\n      setScreen('dashboard');")
r("    return () => unsubscribe();\n  }, []);","    return () => {\n      authSubscription.subscription.unsubscribe();\n      unsubscribe();\n    };\n  }, []);")
r("  const resetSession = () => {\n    window.localStorage.removeItem('user');","  const resetSession = () => {\n    void supabase.auth.signOut().catch(() => undefined);\n    window.localStorage.removeItem('user');")
r("    setScreen('login');\n    setActiveTab('home');","    setAuthSession(null);\n    setScreen('login');\n    setActiveTab('home');")
r("  if (screen === 'dashboard' && appLocked) {","  if (screen === 'dashboard' && !authSession) return null;\n\n  if (screen === 'dashboard' && appLocked) {")
p.write_text(s)
