-- OMNIX persistent messaging foundation.
-- Client access is restricted to conversation members; server-side jobs may use the service role.
create extension if not exists pgcrypto;

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  is_group boolean not null default false,
  name text,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  cleared_at timestamptz,
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  text_content text,
  encrypted_payload text,
  encryption_nonce text,
  sender_ephemeral_public_key text,
  recipient_key_id text,
  encryption_algorithm text,
  is_zero_knowledge boolean not null default false,
  delivery_state text not null default 'sent',
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (text_content is not null or encrypted_payload is not null)
);
create index if not exists messages_conversation_time_idx on public.messages(conversation_id, created_at desc);
create index if not exists messages_sender_idx on public.messages(sender_id, created_at desc);

create table if not exists public.message_reads (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.chat_settings (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  custom_wallpaper text,
  custom_nickname text not null default '',
  is_muted boolean not null default false,
  mute_until timestamptz,
  notification_sound_enabled boolean not null default true,
  vibration_enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.chat_media (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  uploaded_by uuid not null references auth.users(id) on delete cascade,
  storage_path text not null,
  media_type text not null,
  label text,
  created_at timestamptz not null default now()
);
create index if not exists chat_media_conversation_idx on public.chat_media(conversation_id, created_at desc);

alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.message_reads enable row level security;
alter table public.chat_settings enable row level security;
alter table public.chat_media enable row level security;

create policy conversation_members_own_read on public.conversation_members
  for select to authenticated using (auth.uid() = user_id);
create policy conversation_member_visibility on public.conversation_members
  for select to authenticated using (
    exists (select 1 from public.conversation_members cm where cm.conversation_id = conversation_members.conversation_id and cm.user_id = auth.uid())
  );

create policy conversations_member_read on public.conversations
  for select to authenticated using (
    exists (select 1 from public.conversation_members cm where cm.conversation_id = conversations.id and cm.user_id = auth.uid())
  );
create policy conversations_creator_insert on public.conversations
  for insert to authenticated with check (auth.uid() = created_by);

create policy messages_member_read on public.messages
  for select to authenticated using (
    exists (select 1 from public.conversation_members cm where cm.conversation_id = messages.conversation_id and cm.user_id = auth.uid())
  );
create policy messages_sender_insert on public.messages
  for insert to authenticated with check (
    auth.uid() = sender_id and
    exists (select 1 from public.conversation_members cm where cm.conversation_id = messages.conversation_id and cm.user_id = auth.uid())
  );
create policy messages_sender_update on public.messages
  for update to authenticated using (auth.uid() = sender_id) with check (auth.uid() = sender_id);

create policy message_reads_member_access on public.message_reads
  for all to authenticated using (
    auth.uid() = user_id and exists (
      select 1 from public.messages m join public.conversation_members cm on cm.conversation_id = m.conversation_id
      where m.id = message_reads.message_id and cm.user_id = auth.uid()
    )
  ) with check (auth.uid() = user_id);

create policy chat_settings_own on public.chat_settings
  for all to authenticated using (
    auth.uid() = user_id and exists (select 1 from public.conversation_members cm where cm.conversation_id = chat_settings.conversation_id and cm.user_id = auth.uid())
  ) with check (
    auth.uid() = user_id and exists (select 1 from public.conversation_members cm where cm.conversation_id = chat_settings.conversation_id and cm.user_id = auth.uid())
  );

create policy chat_media_member_read on public.chat_media
  for select to authenticated using (
    exists (select 1 from public.conversation_members cm where cm.conversation_id = chat_media.conversation_id and cm.user_id = auth.uid())
  );
create policy chat_media_uploader_insert on public.chat_media
  for insert to authenticated with check (
    auth.uid() = uploaded_by and exists (select 1 from public.conversation_members cm where cm.conversation_id = chat_media.conversation_id and cm.user_id = auth.uid())
  );
