import React, { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../../supabase/supabaseClient';
import { completeSignup, getCurrentSession, loginWithPassword, persistAuthSession, sendSignupOtp, signInWithGoogle, signOut, verifySignupOtp } from '../../utils/authApi';

type Mode = 'login' | 'signup-phone' | 'signup-otp' | 'signup-details' | 'reset-profile';
const pageStyle: React.CSSProperties = { position:'fixed', inset:0, zIndex:10000, overflowY:'auto', display:'flex', alignItems:'center', justifyContent:'center', padding:'24px 16px', background:'#07090d', color:'#f5f7fa', fontFamily:'Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif' };
const shell: React.CSSProperties = { width:'100%', maxWidth:460, padding:'34px 30px 24px', borderRadius:22, background:'#0c1016', border:'1px solid rgba(255,255,255,.09)', boxShadow:'0 20px 70px rgba(0,0,0,.45)' };
const input: React.CSSProperties = { width:'100%', height:52, borderRadius:13, border:'1px solid rgba(255,255,255,.11)', background:'#080b10', color:'#f5f7fa', padding:'0 15px', outline:'none', boxSizing:'border-box', fontSize:15 };
const primary: React.CSSProperties = { width:'100%', minHeight:52, border:0, borderRadius:13, background:'#f5f7fa', color:'#080b10', fontWeight:800, fontSize:15, cursor:'pointer' };
const secondary: React.CSSProperties = { width:'100%', minHeight:50, borderRadius:13, border:'1px solid rgba(255,255,255,.11)', background:'#11161e', color:'#f5f7fa', fontWeight:700, fontSize:14, cursor:'pointer' };
const linkStyle: React.CSSProperties = { color:'#d7dde7', border:0, background:'transparent', padding:0, cursor:'pointer', textDecoration:'underline', textUnderlineOffset:3 };
const friendly = (error: unknown) => error instanceof Error ? error.message : 'Something went wrong. Please try again.';


export function AuthenticationOverlay() {
  const [visible, setVisible] = useState(true); const [mode, setMode] = useState<Mode>('login'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [phone, setPhone] = useState(''); const [countryCode, setCountryCode] = useState('+91'); const [otp, setOtp] = useState(''); const [cooldown, setCooldown] = useState(0); const [showPassword, setShowPassword] = useState(false); const [otpChallengeId, setOtpChallengeId] = useState('');
  const [username, setUsername] = useState(''); const [email, setEmail] = useState(''); const [signupPassword, setSignupPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [legalAccepted, setLegalAccepted] = useState(false); const [googleNeedsProfile, setGoogleNeedsProfile] = useState(false);
  const hadAppSession = useRef(Boolean(window.localStorage.getItem('access_token')));
  const phoneE164 = useMemo(() => { const cc = countryCode.replace(/\D/g, ''); const digits = phone.replace(/\D/g, ''); return cc && digits ? `+${cc}${digits}` : ''; }, [countryCode, phone]);
  useEffect(() => { const timer = window.setInterval(() => setCooldown(value => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { let mounted = true; void getCurrentSession().then(async session => { if (!mounted || !session) return; const { data: profile } = await supabase.from('profiles').select('username').eq('user_id', session.user.id).maybeSingle(); const existingUsername = String(profile?.username || session.user.user_metadata?.username || ''); if (existingUsername) { storeSession(session, existingUsername); hadAppSession.current = true; setVisible(false); } else { setGoogleNeedsProfile(Boolean(session.user.identities?.some((identity: any) => identity.provider === 'google'))); setMode('reset-profile'); } }).catch(() => undefined); return () => { mounted = false; }; }, []);
  useEffect(() => { const { data } = supabase.auth.onAuthStateChange((_event, session) => { if (!session) { setVisible(true); return; } void (async () => { const { data: profile } = await supabase.from('profiles').select('username').eq('user_id', session.user.id).maybeSingle(); const existingUsername = String(profile?.username || session.user.user_metadata?.username || ''); if (existingUsername) { storeSession(session, existingUsername); hadAppSession.current = true; setVisible(false); } else { setMode('reset-profile'); setGoogleNeedsProfile(Boolean(session.user.identities?.some((identity: any) => identity.provider === 'google'))); setVisible(true); } })(); }); return () => data.subscription.unsubscribe(); }, []);
  useEffect(() => { const poll = window.setInterval(() => { const hasToken = Boolean(window.localStorage.getItem('access_token')); if (hasToken) hadAppSession.current = true; if (!hasToken && hadAppSession.current) void signOut(); setVisible(!hasToken); }, 700); return () => window.clearInterval(poll); }, []);

  if (!visible) return null;
  const clearMessages = () => { setError(''); setNotice(''); };
  const switchMode = (next: Mode) => { setMode(next); clearMessages(); if (next === 'signup-phone') { setPhone(''); setOtp(''); setOtpChallengeId(''); setCooldown(0); setLegalAccepted(false); } };
  const handleLogin = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); clearMessages(); try { const response = await loginWithPassword(identifier, password); const session = await getCurrentSession(); if (!session) throw new Error('Login session could not be established.'); storeSession(session, response.user.username || identifier); hadAppSession.current = true; setVisible(false); window.location.reload(); } catch (e) { setError(friendly(e)); } finally { setBusy(false); } };
  const requestOtp = async () => { if (cooldown > 0) return; setBusy(true); clearMessages(); try { if (!phoneE164 || phoneE164.length < 10 || phoneE164.length > 16) throw new Error('Enter a valid phone number.'); const result = await sendSignupOtp(countryCode, phone); setOtpChallengeId(result.challenge_id); setCooldown(60); setMode('signup-otp'); setNotice('OTP sent. Enter the 6-digit code.'); } catch (e) { setError(friendly(e)); } finally { setBusy(false); } };
  const verifyOtp = async () => { setBusy(true); clearMessages(); try { if (!otpChallengeId) throw new Error('Verification session expired. Please request a new code.'); await verifySignupOtp(otpChallengeId, otp); setMode('signup-details'); setNotice('Phone verified. Complete your account details below.'); } catch (e) { setError(friendly(e)); } finally { setBusy(false); } };
  const createAccount = async (event: React.FormEvent) => { event.preventDefault(); if (!legalAccepted) { setError('You must agree to the Terms & Conditions and Privacy Policy.'); return; } if (signupPassword !== confirmPassword) { setError('Passwords do not match.'); return; } setBusy(true); clearMessages(); try { const response = await completeSignup({ username, email, password: signupPassword, phone: phoneE164, legalAccepted }); persistAuthSession(response); hadAppSession.current = true; setVisible(false); window.location.reload(); } catch (e) { setError(friendly(e)); } finally { setBusy(false); } };
  const completeGoogleProfile = async (event: React.FormEvent) => { event.preventDefault(); if (!legalAccepted) { setError('You must agree to the Terms & Conditions and Privacy Policy.'); return; } setBusy(true); clearMessages(); try { const session = await getCurrentSession(); if (!session) throw new Error('Your Google session is no longer active. Please sign in again.'); const cleanUsername = username.trim().toLowerCase(); if (!/^[a-z0-9_]{3,30}$/.test(cleanUsername)) throw new Error('Username must be 3–30 characters using letters, numbers or underscores.'); const { data: existing } = await supabase.from('profiles').select('user_id').eq('username', cleanUsername).maybeSingle(); if (existing?.user_id && existing.user_id !== session.user.id) throw new Error('Username is already taken.'); const { error: updateError } = await supabase.auth.updateUser({ data: { username: cleanUsername, terms_accepted: true, privacy_accepted: true, legal_accepted_at: new Date().toISOString() } }); if (updateError) throw updateError; const { error: profileError } = await supabase.from('profiles').update({ username: cleanUsername, full_name: session.user.user_metadata?.full_name || cleanUsername }).eq('user_id', session.user.id); if (profileError) throw profileError; storeSession(session, cleanUsername); hadAppSession.current = true; setVisible(false); window.location.reload(); } catch (e) { setError(friendly(e)); } finally { setBusy(false); } };

  const title = mode === 'login' ? 'Welcome back' : mode === 'signup-phone' || mode === 'signup-details' ? 'Create your account' : mode === 'signup-otp' ? 'Verify your phone' : 'Finish your profile';
  const subtitle = mode === 'signup-phone' ? 'Enter your mobile number to get started.' : mode === 'signup-otp' ? 'Enter the 6-digit verification code we sent you.' : mode === 'signup-details' ? 'Your phone is verified. Finish setting up your account.' : 'Sign in to continue to OMNIX.';


  return <div style={pageStyle}><div style={shell}>
    <header style={{textAlign:'center',marginBottom:28}}><div style={{fontSize:13,fontWeight:900,letterSpacing:'.28em'}}>OMNIX</div><h1 style={{margin:'18px 0 7px',fontSize:30,lineHeight:1.15,letterSpacing:'-.04em'}}>{title}</h1><p style={{margin:0,color:'#8d98a8',fontSize:14}}>{subtitle}</p></header>
    {error && <div role="alert" style={{marginBottom:16,padding:'11px 13px',borderRadius:11,background:'rgba(239,68,68,.08)',border:'1px solid rgba(239,68,68,.18)',color:'#ffb4b4',fontSize:13}}>{friendly(error)}</div>}
    {notice && <div role="status" style={{marginBottom:16,padding:'11px 13px',borderRadius:11,background:'rgba(255,255,255,.04)',border:'1px solid rgba(255,255,255,.08)',color:'#cbd5e1',fontSize:13}}>{notice}</div>}
    {mode === 'login' && <form onSubmit={handleLogin}><label style={{display:'block',fontSize:12,fontWeight:700,color:'#aab3c0',marginBottom:7}}>Email or phone</label><input style={input} value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="Enter your email or phone" autoComplete="username" required aria-label="Email or phone"/><div style={{height:12}}/><label style={{display:'block',fontSize:12,fontWeight:700,color:'#aab3c0',marginBottom:7}}>Password</label><div style={{position:'relative'}}><input style={{...input,paddingRight:76}} type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password" required aria-label="Password"/><button type="button" onClick={()=>setShowPassword(v=>!v)} style={{position:'absolute',right:10,top:0,height:52,border:0,background:'transparent',color:'#9aa5b4',cursor:'pointer'}}>{showPassword?'Hide':'Show'}</button></div><div style={{display:'flex',justifyContent:'flex-end',margin:'11px 0 18px'}}><button type="button" onClick={()=>{window.location.href='/forgot-password'}} style={linkStyle}>Forgot password?</button></div><button type="submit" disabled={busy} style={{...primary,opacity:busy?.65:1}}>{busy?'Signing in…':'Sign in'}</button><div style={{display:'flex',alignItems:'center',gap:12,margin:'22px 0',color:'#687384',fontSize:12}}><span style={{height:1,background:'rgba(255,255,255,.08)',flex:1}}/><span>OR</span><span style={{height:1,background:'rgba(255,255,255,.08)',flex:1}}/></div><button type="button" onClick={()=>void signInWithGoogle()} disabled={busy} style={secondary}>Continue with Google</button><div style={{textAlign:'center',marginTop:22,color:'#7f8a9a',fontSize:13}}>Don't have an account? <button type="button" onClick={()=>switchMode('signup-phone')} style={{...linkStyle,fontWeight:800}}>Create account</button></div></form>}
    {mode === 'signup-phone' && <form onSubmit={e=>{e.preventDefault();void requestOtp();}}><div style={{display:'grid',gridTemplateColumns:'82px 1fr',gap:9}}><div><label style={{display:'block',fontSize:12,fontWeight:700,color:'#aab3c0',marginBottom:7}}>Code</label><input style={input} value={countryCode} onChange={e=>setCountryCode(e.target.value)} placeholder="+91" inputMode="tel" aria-label="Country code"/></div><div><label style={{display:'block',fontSize:12,fontWeight:700,color:'#aab3c0',marginBottom:7}}>Mobile number</label><input style={input} value={phone} onChange={e=>setPhone(e.target.value)} placeholder="10-digit number" inputMode="tel" autoComplete="tel" aria-label="Mobile number"/></div></div><button type="submit" disabled={busy||cooldown>0} style={{...primary,marginTop:18,opacity:busy?.65:1}}>{busy?'Sending code…':'Continue'}</button><div style={{textAlign:'center',marginTop:20,color:'#7f8a9a',fontSize:13}}>Already have an account? <button type="button" onClick={()=>switchMode('login')} style={{...linkStyle,fontWeight:800}}>Sign in</button></div></form>}
    {mode === 'signup-otp' && <div><label style={{display:'block',fontSize:12,fontWeight:700,color:'#aab3c0',marginBottom:7}}>Verification code</label><input style={{...input,textAlign:'center',letterSpacing:'.42em',fontSize:21}} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000" inputMode="numeric" autoComplete="one-time-code" aria-label="Verification code"/><button type="button" onClick={()=>void verifyOtp()} disabled={busy||otp.length!==6} style={{...primary,marginTop:16,opacity:(busy||otp.length!==6)?.55:1}}>{busy?'Verifying…':'Verify code'}</button><button type="button" onClick={()=>{setMode('signup-phone');setOtp('');clearMessages();}} style={{...secondary,marginTop:10}}>Back</button><button type="button" onClick={()=>void requestOtp()} disabled={busy||cooldown>0} style={{width:'100%',marginTop:13,border:0,background:'transparent',color:'#b9c2cf',cursor:'pointer'}}>{cooldown>0?'Resend in '+cooldown+'s':'Resend code'}</button></div>}
    {mode === 'signup-details' && <form onSubmit={createAccount}><div style={{display:'flex',gap:5,marginBottom:22}}>{[1,2,3].map(n=><div key={n} style={{height:3,flex:1,borderRadius:9,background:'#f5f7fa'}}/>)}</div><div style={{display:'grid',gap:11}}><input style={input} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" autoComplete="username" required aria-label="Username"/><input style={input} type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" autoComplete="email" required aria-label="Email address"/><input style={input} type="password" value={signupPassword} onChange={e=>setSignupPassword(e.target.value)} placeholder="Password (8+ characters)" autoComplete="new-password" required aria-label="Password"/><input style={input} type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Confirm password" autoComplete="new-password" required aria-label="Confirm password"/></div><label style={{display:'flex',gap:9,alignItems:'flex-start',color:'#9ca7b6',fontSize:12,lineHeight:1.5,margin:'17px 0'}}><input type="checkbox" checked={legalAccepted} onChange={e=>setLegalAccepted(e.target.checked)} style={{marginTop:3}}/><span>By creating an account, you agree to our <a href="/terms" style={{color:'#e5e7eb',textDecoration:'underline'}}>Terms &amp; Conditions</a> and <a href="/privacy" style={{color:'#e5e7eb',textDecoration:'underline'}}>Privacy Policy</a>.</span></label><button type="submit" disabled={busy||!legalAccepted} style={{...primary,opacity:(busy||!legalAccepted)?.55:1}}>{busy?'Creating account…':'Create account'}</button><div style={{textAlign:'center',marginTop:20,color:'#7f8a9a',fontSize:13}}>Already have an account? <button type="button" onClick={()=>switchMode('login')} style={{...linkStyle,fontWeight:800}}>Sign in</button></div></form>}
    {mode === 'reset-profile' && <form onSubmit={completeGoogleProfile}><p style={{color:'#aab3c0',fontSize:14,lineHeight:1.6,marginTop:0}}>{googleNeedsProfile?'Google authentication succeeded. Choose your OMNIX username before entering the app.':'Choose the username that will identify your OMNIX profile.'}</p><input style={input} value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" autoComplete="username" required aria-label="Username"/><label style={{display:'flex',gap:9,alignItems:'flex-start',color:'#9ca7b6',fontSize:12,lineHeight:1.5,margin:'17px 0'}}><input type="checkbox" checked={legalAccepted} onChange={e=>setLegalAccepted(e.target.checked)} style={{marginTop:3}}/><span>I agree to the <a href="/terms" style={{color:'#e5e7eb'}}>Terms &amp; Conditions</a> and <a href="/privacy" style={{color:'#e5e7eb'}}>Privacy Policy</a>.</span></label><button type="submit" disabled={busy||!legalAccepted} style={{...primary,opacity:(busy||!legalAccepted)?.55:1}}>{busy?'Saving…':'Continue to OMNIX'}</button></form>}
    <footer style={{textAlign:'center',marginTop:28,paddingTop:18,borderTop:'1px solid rgba(255,255,255,.07)',color:'#687384',fontSize:11,lineHeight:1.5}}>Secure account access · <a href="/terms" style={{color:'#9ca7b6'}}>Terms &amp; Conditions</a> · <a href="/privacy" style={{color:'#9ca7b6'}}>Privacy Policy</a></footer>
  </div></div>;
