import React, { useEffect, useState } from 'react';
import { supabase } from '../../supabase/supabaseClient';
import { requestPasswordReset, updatePassword } from '../../utils/authApi';

export function PasswordRecoveryOverlay() {
  const [active, setActive] = useState(window.location.pathname === '/forgot-password' || window.location.search.includes('auth=forgot'));
  const [recoverySession, setRecoverySession] = useState(false);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState('');
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const card: React.CSSProperties = { width: '100%', maxWidth: 430, padding: 28, borderRadius: 24, background: 'rgba(16,22,38,.82)', border: '1px solid rgba(148,163,184,.22)', boxShadow: '0 24px 80px rgba(0,0,0,.45)', backdropFilter: 'blur(24px)', color: '#f8fafc' };
  const field: React.CSSProperties = { width: '100%', height: 48, borderRadius: 12, border: '1px solid rgba(148,163,184,.22)', background: 'rgba(15,23,42,.72)', color: '#f8fafc', padding: '0 14px', boxSizing: 'border-box', outline: 'none' };
  const primary: React.CSSProperties = { width: '100%', minHeight: 48, marginTop: 12, border: 0, borderRadius: 12, background: 'linear-gradient(135deg,#06b6d4,#2563eb)', color: '#fff', fontWeight: 800, cursor: 'pointer' };

  useEffect(() => {
    const { data } = supabase.auth.onAuthStateChange(event => {
      if (event === 'PASSWORD_RECOVERY') { setRecoverySession(true); setActive(true); setError(''); setMessage('Recovery link verified. Choose a new password.'); }
    });
    void supabase.auth.getSession().then(({ data: sessionData }) => { if (sessionData.session && window.location.hash.includes('access_token')) setRecoverySession(true); }).catch(() => undefined);
    return () => data.subscription.unsubscribe();
  }, []);

  if (!active) return null;
  const request = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { await requestPasswordReset(email); setMessage('If the account exists, a password recovery email has been sent. Check your inbox and open the link.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to request password reset.'); } finally { setBusy(false); } };
  const reset = async (event: React.FormEvent) => { event.preventDefault(); if (password.length < 8) { setError('Password must be at least 8 characters.'); return; } if (password !== confirm) { setError('Passwords do not match.'); return; } setBusy(true); setError(''); try { await updatePassword(password); await supabase.auth.signOut(); window.history.replaceState({}, '', '/'); window.location.reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update password.'); } finally { setBusy(false); } };
  return <div style={{ position: 'fixed', inset: 0, zIndex: 12000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20, overflowY: 'auto', background: 'radial-gradient(circle at 20% 10%,rgba(6,182,212,.12),transparent 35%),radial-gradient(circle at 80% 90%,rgba(99,102,241,.12),transparent 35%),#070b14', fontFamily: 'Inter,system-ui,sans-serif' }}><div style={card}><div style={{ textAlign: 'center', marginBottom: 24 }}><div style={{ fontSize: 11, letterSpacing: '.22em', color: '#67e8f9', fontWeight: 800 }}>OMNIX</div><h1 style={{ margin: '8px 0 6px', fontSize: 28, letterSpacing: '-.04em' }}>{recoverySession ? 'Set new password' : 'Forgot Password'}</h1><p style={{ margin: 0, color: '#94a3b8', fontSize: 13 }}>{recoverySession ? 'Choose a new password for your OMNIX account.' : 'Enter your email and we will send a secure recovery link.'}</p></div>{!recoverySession ? <form onSubmit={request}><input style={field} type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email address" autoComplete="email" required /><button disabled={busy} style={{ ...primary, opacity: busy ? .7 : 1 }}>{busy ? 'Sending…' : 'Send Recovery Email'}</button></form> : <form onSubmit={reset}><input style={{ ...field, marginBottom: 10 }} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="New password (8+ characters)" autoComplete="new-password" required /><input style={field} type="password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="Confirm new password" autoComplete="new-password" required /><button disabled={busy} style={{ ...primary, opacity: busy ? .7 : 1 }}>{busy ? 'Updating…' : 'Update Password'}</button></form>}{message && <div style={{ marginTop: 14, padding: '10px 12px', borderRadius: 10, background: 'rgba(34,197,94,.08)', color: '#86efac', fontSize: 12 }}>{message}</div>}{error && <div role="alert" style={{ marginTop: 14, padding: '10px 12px', borderRadius: 10, background: 'rgba(239,68,68,.1)', color: '#fca5a5', fontSize: 12 }}>{error}</div>}<button type="button" onClick={() => { window.location.href = '/'; }} style={{ width: '100%', marginTop: 16, minHeight: 44, borderRadius: 12, border: '1px solid rgba(148,163,184,.22)', background: 'transparent', color: '#cbd5e1', cursor: 'pointer' }}>Back to Log In</button></div></div>;
}
