import React, { useEffect, useMemo, useState } from 'react';
import { apiJson } from '../../utils/socialApi';
import { prefetchMedia } from '../../utils/mediaCache';

interface Post { id: string; author: string; likes: number; caption: string; tags: string[]; mentions: string[]; location: string; visibility?: string; created_at?: string; image_url?: string | null; comments_count?: number; impression_count?: number; shares_count?: number; }
type FeedFilter = 'all' | 'followers' | 'private';

export function HomeFeed({ onInteraction }: { onInteraction: (type: string, tag: string) => void }) {
  const [posts, setPosts] = useState<Post[]>([]); const [likedPosts, setLikedPosts] = useState<string[]>([]); const [dislikedPosts, setDislikedPosts] = useState<string[]>([]);
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(''); const [filter, setFilter] = useState<FeedFilter>('all');
  const [privacyMode, setPrivacyMode] = useState<'public' | 'followers' | 'private'>('public'); const [draftPost, setDraftPost] = useState(''); const [posting, setPosting] = useState(false);
  const [commentInputs, setCommentInputs] = useState<Record<string, string>>({}); const [statusMessage, setStatusMessage] = useState(''); const [feedOffset, setFeedOffset] = useState(0); const [loadingMore, setLoadingMore] = useState(false);

  const mapPost = (post: Record<string, unknown>): Post => ({ id: typeof post.id === 'string' ? post.id : '', author: typeof post.username === 'string' ? post.username : (post.user_id ? `user_${String(post.user_id).slice(0, 6)}` : 'unknown'), likes: typeof post.likes === 'number' ? post.likes : 0, caption: typeof post.content === 'string' ? post.content : '', tags: Array.isArray(post.tags) ? post.tags.filter((tag): tag is string => typeof tag === 'string') : [], mentions: Array.isArray(post.mentions) ? post.mentions.filter((mention): mention is string => typeof mention === 'string') : [], location: typeof post.location === 'string' ? post.location : '', visibility: typeof post.visibility === 'string' ? post.visibility : 'public', created_at: typeof post.created_at === 'string' ? post.created_at : undefined, image_url: typeof post.image_url === 'string' ? post.image_url : null, comments_count: typeof post.comments_count === 'number' ? post.comments_count : 0, shares_count: typeof post.shares_count === 'number' ? post.shares_count : 0, impression_count: typeof post.impression_count === 'number' ? post.impression_count : 0 });

  const trackEvent = async (postId: string, interactionType: string, metadata: Record<string, unknown> = {}) => apiJson('/api/posts/' + postId + '/interactions', { method: 'POST', body: JSON.stringify({ interaction_type: interactionType, metadata }) });

  const loadPosts = async (offset = 0, append = false) => {
    const data = await apiJson<{ success: boolean; posts: Record<string, unknown>[] }>('/api/posts/feed', { query: { limit: 5, offset } });
    if (!data?.success) throw new Error('Feed request failed');
    const mapped = (data.posts ?? []).map(mapPost).filter((post) => Boolean(post.id));
    setPosts((current) => append ? [...current, ...mapped.filter((item) => !current.some((existing) => existing.id === item.id))] : mapped);
    setFeedOffset(offset + mapped.length); void prefetchMedia(mapped.slice(0, 5).map((item) => item.image_url ?? '').filter(Boolean), 5);
    if (!append) for (const item of mapped) void trackEvent(item.id, 'impression', { source: 'home_feed' }).catch(() => undefined);
    return mapped.length;
  };

  useEffect(() => { let cancelled = false; (async () => { setLoading(true); setLoadError(''); try { if (!cancelled) await loadPosts(); } catch (error) { if (!cancelled) { console.error('Unable to load feed posts', error); setPosts([]); setFeedOffset(0); setLoadError(error instanceof Error ? error.message : 'Unable to load feed right now.'); } } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, []);

  const retryFeed = async () => { setLoading(true); setLoadError(''); try { await loadPosts(); } catch (error) { setPosts([]); setFeedOffset(0); setLoadError(error instanceof Error ? error.message : 'Unable to load feed right now.'); } finally { setLoading(false); } };
  const loadMore = async () => { if (loadingMore) return; setLoadingMore(true); setLoadError(''); try { await loadPosts(feedOffset, true); } catch (error) { setLoadError(error instanceof Error ? error.message : 'Unable to load more posts.'); } finally { setLoadingMore(false); } };
  const toggledPosts = useMemo(() => posts.filter((post) => filter === 'followers' ? (post.visibility === 'followers' || post.visibility === 'public') : filter === 'private' ? post.visibility === 'private' : true), [filter, posts]);

  const handleCreatePost = async (event: React.FormEvent) => { event.preventDefault(); if (!draftPost.trim() || posting) return; setPosting(true); setStatusMessage(''); try { const data = await apiJson<{ success: boolean }>('/api/posts', { method: 'POST', body: JSON.stringify({ content: draftPost.trim(), image_url: null, visibility: privacyMode, location: '', tags: [], mentions: [] }) }); if (!data.success) throw new Error('Post creation failed'); setDraftPost(''); setStatusMessage('Post published.'); await loadPosts(); } catch (error) { setStatusMessage(error instanceof Error ? error.message : 'Unable to create post now'); } finally { setPosting(false); } };

  const handleLike = async (postId: string, tags: string[]) => { if (!postId) return; const currentlyLiked = likedPosts.includes(postId); setLikedPosts((current) => currentlyLiked ? current.filter((id) => id !== postId) : [...current, postId]); setDislikedPosts((current) => current.filter((id) => id !== postId)); try { await trackEvent(postId, currentlyLiked ? 'dislike' : 'like', { tags }); onInteraction(currentlyLiked ? 'Unlike Triggered' : 'Like Action Registered', tags.join(', ')); await loadPosts(); } catch (error) { setLikedPosts((current) => currentlyLiked ? [...current, postId] : current.filter((id) => id !== postId)); setStatusMessage(error instanceof Error ? error.message : 'Unable to update like.'); } };
  const handleDislike = async (postId: string) => { if (!postId) return; const currentlyDisliked = dislikedPosts.includes(postId); setDislikedPosts((current) => currentlyDisliked ? current.filter((id) => id !== postId) : [...current, postId]); if (!currentlyDisliked) setLikedPosts((current) => current.filter((id) => id !== postId)); try { await trackEvent(postId, 'dislike', { source: 'feed_action' }); onInteraction('Dislike Triggered', postId); await loadPosts(); } catch (error) { setStatusMessage(error instanceof Error ? error.message : 'Unable to update reaction.'); } };
  const handleShare = async (postId: string) => { if (!postId) return; try { await trackEvent(postId, 'share', { destination: 'native_sheet' }); setStatusMessage('Share recorded.'); onInteraction('Share Triggered', postId); await loadPosts(); } catch (error) { setStatusMessage(error instanceof Error ? error.message : 'Unable to share now'); } };
  const handleComment = async (postId: string) => { const nextComment = (commentInputs[postId] || '').trim(); if (!postId || !nextComment) return; try { await apiJson(`/api/posts/${postId}/comments`, { method: 'POST', body: JSON.stringify({ comment: nextComment }) }); setCommentInputs((current) => ({ ...current, [postId]: '' })); setStatusMessage('Comment posted.'); onInteraction('Comment Added', postId); await loadPosts(); } catch (error) { setStatusMessage(error instanceof Error ? error.message : 'Unable to comment now'); } };

  return <div style={{ maxWidth: '470px', margin: '0 auto', width: '100%', boxSizing: 'border-box', padding: '10px 0' }}>
    <form onSubmit={handleCreatePost} style={{ display: 'flex', gap: '8px', padding: '0 14px 12px' }}><input type="text" value={draftPost} onChange={(event) => setDraftPost(event.target.value)} placeholder="Share a secure update..." maxLength={5000} style={{ flex: 1, padding: '10px 12px', borderRadius: '999px', border: '1px solid #334155', background: '#0f172a', color: '#f8fafc', outline: 'none' }} /><button type="submit" disabled={posting || !draftPost.trim()} style={{ borderRadius: '999px', border: 'none', background: '#7c3aed', color: '#fff', padding: '10px 12px', cursor: posting ? 'wait' : 'pointer', opacity: posting || !draftPost.trim() ? 0.5 : 1 }}>{posting ? 'Posting…' : 'Post'}</button></form>
    <div style={{ display: 'flex', gap: '8px', padding: '0 14px 10px', flexWrap: 'wrap' }}>{(['public', 'followers', 'private'] as const).map((mode) => <button key={mode} type="button" onClick={() => setPrivacyMode(mode)} style={{ borderRadius: '999px', border: privacyMode === mode ? '1px solid #38bdf8' : '1px solid #1f2937', background: privacyMode === mode ? '#0f3a4f' : '#0f172a', color: '#f8fafc', padding: '6px 10px', cursor: 'pointer', textTransform: 'capitalize' }}>{mode}</button>)}</div>
    {statusMessage ? <div role="status" style={{ padding: '0 14px 10px', color: '#7dd3fc', fontSize: '12px' }}>{statusMessage}</div> : null}
    {loadError ? <div role="alert" style={{ margin: '0 14px 16px', padding: '12px', border: '1px solid #7f1d1d', borderRadius: '12px', color: '#fecaca', background: '#1c0b0b' }}><div>{loadError}</div><button type="button" onClick={() => void retryFeed()} disabled={loading} style={{ marginTop: '8px', borderRadius: '999px', border: '1px solid #334155', background: 'transparent', color: '#fff', padding: '6px 10px', cursor: 'pointer' }}>Retry</button></div> : null}
    {loading ? <div aria-live="polite" style={{ padding: '14px', color: '#94a3b8' }}>Loading secure feed…</div> : toggledPosts.length === 0 ? <div style={{ padding: '14px', color: '#94a3b8' }}>No posts are available in this view yet.</div> : toggledPosts.map((post) => <div key={post.id} style={{ marginBottom: '24px', borderBottom: '1px solid #121212' }}>
      <div style={{ display: 'flex', alignItems: 'center', padding: '12px 14px', gap: '10px' }}><div style={{ width: '32px', height: '32px', borderRadius: '50%', backgroundColor: '#262626', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '10px', color: '#a855f7' }}>{post.author.slice(0, 2).toUpperCase()}</div><div><div style={{ fontSize: '13px', fontWeight: '600' }}>{post.author}</div><div style={{ fontSize: '10px', color: '#8e8e8e' }}>{post.location || 'Secure feed'} • {post.visibility}</div></div></div>
      {post.image_url ? <img src={post.image_url} alt="Post media" loading="lazy" style={{ width: '100%', aspectRatio: '1/1', objectFit: 'cover', display: 'block' }} /> : <div style={{ width: '100%', aspectRatio: '1/1', backgroundColor: '#0a0a0a', display: 'flex', alignItems: 'center', justifyContent: 'center', border: '1px solid #121212' }}><span style={{ color: '#64748b', fontSize: '13px' }}>No media</span></div>}
      <div style={{ padding: '12px 14px' }}><div style={{ display: 'flex', gap: '16px', marginBottom: '8px', alignItems: 'center' }}><button type="button" aria-label={likedPosts.includes(post.id) ? 'Unlike post' : 'Like post'} onClick={() => void handleLike(post.id, post.tags)} style={{ border: 0, background: 'transparent', padding: 0, cursor: 'pointer' }}><svg width="24" height="24" viewBox="0 0 24 24" fill={likedPosts.includes(post.id) ? '#ef4444' : 'none'} stroke={likedPosts.includes(post.id) ? '#ef4444' : 'currentColor'} strokeWidth="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" /></svg></button><button type="button" onClick={() => void handleDislike(post.id)} style={{ borderRadius: '999px', border: dislikedPosts.includes(post.id) ? '1px solid #f59e0b' : '1px solid #334155', background: 'transparent', color: '#f8fafc', padding: '3px 9px', cursor: 'pointer', fontSize: '11px' }}>Dislike</button><button type="button" onClick={() => void handleShare(post.id)} style={{ borderRadius: '999px', border: '1px solid #334155', background: 'transparent', color: '#f8fafc', padding: '3px 9px', cursor: 'pointer', fontSize: '11px' }}>Share</button></div><div style={{ fontSize: '13px', fontWeight: '600', marginBottom: '4px' }}>{post.likes} likes</div><div style={{ fontSize: '13px', lineHeight: '1.4', color: '#f5f5f5' }}><b>{post.author}</b>{post.caption ? ` ${post.caption}` : ''}</div><div style={{ marginTop: '6px', fontSize: '11px', color: '#94a3b8' }}>{post.comments_count ?? 0} comments • {post.shares_count ?? 0} shares • {post.impression_count ?? 0} impressions</div><div style={{ marginTop: '8px', display: 'flex', gap: '8px' }}><input type="text" value={commentInputs[post.id] ?? ''} onChange={(event) => setCommentInputs((current) => ({ ...current, [post.id]: event.target.value }))} placeholder="Add a comment" maxLength={2000} style={{ flex: 1, borderRadius: '999px', border: '1px solid #334155', background: '#020617', color: '#f8fafc', padding: '7px 10px', outline: 'none', fontSize: '12px' }} /><button type="button" onClick={() => void handleComment(post.id)} disabled={!commentInputs[post.id]?.trim()} style={{ borderRadius: '999px', border: '1px solid #334155', background: 'transparent', color: '#f8fafc', padding: '6px 10px', cursor: 'pointer', fontSize: '12px', opacity: commentInputs[post.id]?.trim() ? 1 : 0.5 }}>Comment</button></div></div>
    </div>)}
    {!loading && toggledPosts.length >= 5 ? <button type="button" onClick={() => void loadMore()} disabled={loadingMore} style={{ margin: '4px 14px 18px', width: 'calc(100% - 28px)', padding: '10px', borderRadius: '999px', border: '1px solid #334155', background: '#0f172a', color: '#f8fafc', cursor: loadingMore ? 'wait' : 'pointer' }}>{loadingMore ? 'Loading…' : 'Load 5 more'}</button> : null}
  </div>;
}
